language: node_js
node_js:
  - "10.6.0"
sudo: required
services:
- docker
script:
- yarn install
- yarn run build:library
before_deploy:
  - cd dist/payment-lib
deploy:
  skip_cleanup: true
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: TvoMvfiolI9M4G7jP6tIkKsy6DRjKi/2+ahnxBfPFS8zBJUnWW1SLAMsrDotGePY8poFsusiuHh7z9tqLdJtdu9sQRLvAJfv3kU7t3BOXbnPCYRk2OQVI4rGhmC5yI3K13WF1/ynP3bgeks04UkbVDAJWBzapTNyiJjpt/6I6NBtM2L6u9tOO8sc1Qm3UhAoCINJkiDr5jTVQXoNf/+pDR2mUsCi+/hhNj99ghAtvaC2qRT0iLb40mXpv0hCKw76KX94NG2in/TDbb0mjXFNL7XZ7zXNVM1mzFI2ylaFxCKTVpNX9fMuC30Cv+yPFntsJPS/GG7T4R2jb1dbvKKSW2DTRwPCqeQssEnmAI5y8BrJjLiZsm+RvOplaO9e6TRzHymVr9DP5qzFnHa41XtWbMbQLILJMSqnzHvvuZaXuW2MsAkeuI2BLXdU4/KPpnjNray4TSPoIup/l+r241mdquRUHrlDE6VqQIqm+PAjwqCN7kpkJFg99ifWV2vkAUQM3iiguYHuoHgPmH6bGcr5OC5GVNEpf6kZ5Mb4VKCZ2Qbu1ztUzhhta1GjMNSHgpKymf7TwF8mLNhkpMrn6woyToEDxZzjSipRExianyZu1QvzYkqmfzU2jS2mFl50R9OAgn/v6ugMNcbrJfzhnSh9dn3tZkJSmHcFJcwWLKkPgEI=
  on:
    tags: true
repo: hmcts/ccpay-web-component
