language: node_js
node_js:
  - "10.6.0"
sudo: required
services:
- docker
script:
- yarn install
- yarn run build:library
before_deploy:
  - cd dist/payment-lib
deploy:
  skip_cleanup: true
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: eukL/vESdKEitoJXx0QcCJnTZhTnOu/+UAZIsbFZoQ3ne1A7U7sX+s10mYiVlI8dPSV8TTHWUZrz1sq+RmaDHtpA/MHfa/Tgzs6pX3Z+I05dVog2RMH51Cr1Ox3i91dE9AE+ylQbB3dsDgawCusuvSldSKx5wyNW/NWmen1uS0XhU205RHAbaDG/b/IT43AWf3mFJ0j1OKCXvElFkVk5RsjiZO1bEXSdzEo5DV36TOo93TlAW6EgKudJpUjlA+leFjuZlvkZ30s3An8d1FFM5r+3TXuC+MY34VQLKcNlPqHiGZQ77khrooFLYrGhLI9Lah8R1LXoBMeEmNsRUULjy0lWDkQhRaTt/Vj+0sLr9TTNexs368QxMyOnmWhHJRhGUcCWCnKgs4HhaLp5LlaXhodazGb/BPLonC+afoJxe1qSYd1v3oYgTuURl25IHmgc0atI6b/OBy9IF1kGPLYY6g6y9hMj4iY2+mYfbm93v16cS+RLf9vAWi9joQ3OhZj49HLDfC84tPgoA5n++OPX8C0Dvwsl+bXFaumbRNgP9zj0SwkWHZvN5vtXdy+cl81F3zgoqdE01D1U8ZfwlKV5u8RVmolCWTpFA40gFpCFCrvALDVhkKP4n9qelf92IZQ2dLKiTmduIGJeDVHecBjfKjwyKDt+t8ZnHxEkR+e6hLk=
  on:
    tags: true
repo: hmcts/ccpay-web-component
